services:
  # Postgres Configuration
  postgres:
    image: postgres:12
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    command: -p ${DATABASE_PORT}
  # Gateway Configuration
  server:
    build:
      context: .
      dockerfile: ./docker/gateway.dockerfile
    links:
      - postgres
    ports: 
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    
volumes:
  database: