services:
  # Postgres Configuration
  postgres:
    image: postgres:12
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  # Redis Configuration
  cache:
    image: redis:6
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - 6379:6379
  # Gateway Configuration
  server:
    build:
      context: .
      dockerfile: ./docker/gateway.dockerfile
    links:
      - cache
      - postgres
    ports: 
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    
volumes:
  database:
  redis: