#https://serverless.com/framework/docs/providers/aws/guide/serverless.yml

service: arweave-gateway

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  endpointType: regional
  memorySize: 1536
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rds-db:connect
      Resource:
        - arn:aws:rds-db:${self:provider.region, 'eu-west-2'}:384386061638:dbuser:*/*
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectTagging
      Resource:
        - arn:aws:s3:::${self:service}-${opt:stage, 'dev'}-*/*
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:DeleteMessage
        - sqs:DeleteMessageBatch
      Resource:
        - arn:aws:sqs:${self:provider.region, 'eu-west-2'}:384386061638:${self:service}-${opt:stage, 'dev'}-*
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - arn:aws:sns:${self:provider.region, 'eu-west-2'}:384386061638:${self:service}-${opt:stage, 'dev'}-*

  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    minimumCompressionSize: 1024
  logs:
    restApi: true
  stackTags:
    Service: ${self:service}
    Environment: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:service}-deployments-${self:provider.region, 'eu-west-2'}
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  environment:
    ARWEAVE_GATEWAY_ORIGINS: '["http://lon-1.eu-west-1.arweave.net:1984","http://lon-2.eu-west-1.arweave.net:1984","http://lon-3.eu-west-1.arweave.net:1984","http://lon-4.eu-west-1.arweave.net:1984","http://lon-5.eu-west-1.arweave.net:1984","http://lon-6.eu-west-1.arweave.net:1984"]'
    ARWEAVE_SNS_EVENTS_ARN: ${self:custom.events.topicArn}
    ARWEAVE_SQS_DISPATCH_TXS_URL: https://sqs.${self:provider.region, 'eu-west-2'}.amazonaws.com/384386061638/${self:custom.queues.dispatchTxs}
    ARWEAVE_SQS_IMPORT_TXS_URL: https://sqs.${self:provider.region, 'eu-west-2'}.amazonaws.com/384386061638/${self:custom.queues.importTxs}
    ARWEAVE_SQS_IMPORT_BLOCKS_URL: https://sqs.${self:provider.region, 'eu-west-2'}.amazonaws.com/384386061638/${self:custom.queues.importBlocks}.fifo
    ARWEAVE_S3_TX_DATA_BUCKET: ${self:custom.buckets.txData}
    ARWEAVE_DB_READ_HOST: arweave-gateway-dev.cluster-cxjgmvwj8379.eu-west-2.rds.amazonaws.com
    ARWEAVE_DB_WRITE_HOST: arweave-gateway-dev.cluster-cxjgmvwj8379.eu-west-2.rds.amazonaws.com
    ARWEAVE_DB_SCHEMA: arweave

plugins:
  - serverless-api-gateway-caching
  - serverless-domain-manager
  - serverless-stage-manager
  - serverless-deployment-bucket
  # - serverless-offline-sqs
  - serverless-offline

functions:
  api:
    handler: dist/gateway/api/index.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true
          request:
            parameters:
              paths:
                proxy: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.proxy
            perKeyInvalidation:
              requireAuthorization: true
              handleUnauthorizedRequests: Ignore

  api-new-tx:
    handler: dist/gateway/new-tx/index.handler
    events:
      - http:
          path: tx
          method: post
          cors: true

  api-webhooks:
    handler: dist/gateway/webhooks/index.handler
    events:
      - http:
          path: webhook
          method: post
          cors: true

  api-arql:
    handler: dist/gateway/arql/index.handler
    events:
      - http:
          path: arql
          method: post
          cors: true

  api-graphql:
    handler: dist/gateway/graphql/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true

  dispatch-txs:
    handler: dist/jobs/dispatch-txs.handler
    timeout: 60
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [SQSDispatchTxsQueue, Arn]

  import-txs:
    handler: dist/jobs/import-txs.handler
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [SQSImportTxsQueue, Arn]

  import-blocks:
    handler: dist/jobs/import-blocks.handler
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt: [SQSImportBlocksQueue, Arn]

package:
  exclude:
    - terraform/**
  include:
    - dist/**

custom:
  events:
    topic: ${self:service}-${opt:stage, 'dev'}-events
    topicArn: arn:aws:sns:${self:provider.region, 'eu-west-2'}:384386061638:${self:service}-${opt:stage, 'dev'}-events
  queues:
    dispatchTxs: ${self:service}-${opt:stage, 'dev'}-dispatch-txs
    importTxs: ${self:service}-${opt:stage, 'dev'}-import-txs
    importBlocks: ${self:service}-${opt:stage, 'dev'}-import-blocks
  buckets:
    txData: ${self:service}-${opt:stage, 'dev'}-tx-data-${self:provider.region, 'eu-west-2'}
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: "2012-11-05"
    endpoint: http://0.0.0.0:9324
    region: eu-west-2
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

  stages:
    - dev
    - prod
  apiGatewayCaching:
    enabled: true
    clusterSize: "0.5"
    ttlInSeconds: 30
    dataEncrypted: false
    perKeyInvalidation:
      requireAuthorization: true
      handleUnauthorizedRequests: Ignore
  customDomain:
    domainName: ${file(serverless.${opt:stage, 'dev'}.yml):domain}
    stage: ${opt:stage, 'dev'}
    certificateName: ${file(serverless.${opt:stage, 'dev'}.yml):domain}
    certificateRegion: ${self:provider.region, 'eu-west-2'}
    createRoute53Record: false
    endpointType: regional
    securityPolicy: tls_1_2
    enabled: true

  serverless-offline:
    httpPort: 3000
    resourceRoutes: true

resources:
  Resources:
    SNSEventsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "Events topic (${opt:stage, 'dev'}-tx-data-${self:provider.region, 'eu-west-2'}) - Managed by Serverless + CloudFormation"
        TopicName: ${self:custom.events.topic}

    S3TxDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.buckets.txData}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          RestrictPublicBuckets: true
          IgnorePublicAcls: true

    SQSDispatchTxsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queues.dispatchTxs}
        MessageRetentionPeriod: 1209600 #14 days in seconds, max supported value
        ReceiveMessageWaitTimeSeconds: 10
        VisibilityTimeout: 60
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [SQSDispatchTxsDLQ, Arn]
          maxReceiveCount: 2

    SQSDispatchTxsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queues.dispatchTxs}-DLQ
        MessageRetentionPeriod: 1209600 #14 days, max

    SQSImportTxsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queues.importTxs}
        MessageRetentionPeriod: 1209600 #14 days in seconds, max supported value
        ReceiveMessageWaitTimeSeconds: 10
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [SQSImportTxsDLQ, Arn]
          maxReceiveCount: 2

    SQSImportTxsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queues.importTxs}-DLQ
        MessageRetentionPeriod: 1209600 #14 days, max

    SQSImportBlocksQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queues.importBlocks}.fifo
        FifoQueue: true
        MessageRetentionPeriod: 1209600 #14 days in seconds, max supported value
        ReceiveMessageWaitTimeSeconds: 10
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [SQSImportBlocksDLQ, Arn]
          maxReceiveCount: 2

    SQSImportBlocksDLQ:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: ${self:custom.queues.importBlocks}-DLQ.fifo
        MessageRetentionPeriod: 1209600 #14 days, max
