CREATE USER read;
CREATE USER write;

GRANT rds_iam to read;
GRANT rds_iam to write;

GRANT CONNECT ON DATABASE arweave TO read;
GRANT CONNECT ON DATABASE arweave TO write;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO read;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO write;
